### PR TITLE
Simplify tweet column assignment

### PR DESCRIPTION
**Pull request by stephen-lt-sl**

### CODE REVIEW

**Review by BRHoward — APPROVED** [review]
looks good once the tests pass

**Comment by susanthomson** [comment]
Are the three column templates identical now?

**Comment by stephen-lt-sl** [comment]
Almost; the only real difference is that the left column has an image at the head - I was thinking of merging them and finding some other way to add the image, but I figured we might want to make other changes to specific columns in future anyway, so it'd be better to leave it for now (at least until we have the UX worked out better)

**Comment by susanthomson** [comment]
Ah yeah, the image tags were helpfully hidden by github. I think leaving it for now is fair. :+1:

**Review by susanthomson — APPROVED** [review]

**Pull request merged**
