### PR TITLE
send speaker update for official user

### PR DESCRIPTION
**Pull request by susanthomson**
Bristech tweets will be tagged with wallPriority client side but bristech does not appear in list of speakers.

### CODE REVIEW

**Comment by susanthomson** [comment]
forgot to test :blush:

**Review by stephen-lt-sl — COMMENTED** [review]
It'd make more sense to do officialUsers.forEach(add an update), since otherwise this doesn't work with more than one official user (it could happen!)

**Review by BRHoward — APPROVED** [review]

**Comment by susanthomson** [comment]
More than one official user doesn't really work though, we pull tweets from the timeline of an official user and if you put more than one in it just ignores it. Probably best to make an officialUser string rather than officialUsers array since it's quite misleading.

**Review by stephen-lt-sl — APPROVED** [review]
Fair enough then, we can just change that sometime later then.

**Pull request merged**
