### PR TITLE
Overall design

### PR DESCRIPTION
**Pull request by Geor23**

### CODE REVIEW

**Comment by susanthomson** [comment]
screenshot-7-10-16-08084

**Comment by susanthomson** [comment]
It seems to have a problem with some sizes of picture
screenshot-7-10-16-0909

**Comment by Geor23** [comment]
well how do i get that particular picture that it doesn't work for so i can see what the problem is?

**Comment by susanthomson** [comment]
In that screenshot it's this one https://twitter.com/jonathanjacob/status/784267667519614982 but I've seen it do that with other pictures that are that same shape of portrait mobile screenshots.

**Pull request closed without merging**
